export const TEXT = {
    HM1: 'Highly motivated and a persistent problem-solver. I`m detail oriented and passionate about building backend data services, API`s and microservices. Currently working as a Software Engineer at DELL. Willing to keep learning new technologies, frameworks and best practices.',
    ABT1: 'I’m Bruna Prauchner. Born in Porto Alegre (Brazil) and raised in a small town called Eldorado do Sul. I studied Computer Science at PUCRS. At the beginning of university I wanted to study english abroad to enhance my communication skills thus I went to Australia. I arrived on the other side of the world completely alone that made me realize everyday has a surprise it can be good or bad we have to know how to deal with both sides of the coin. Going out of your comfort zone is an addictive feeling and to put that in practice when I came back I decided to do volunteer work, thenceforth I`m addicted to experiences that can broaden my horizons. Fast-forward to today I work as Software Engineer at DELL in a multicultural team to delivers innovative payment solutions, allowing organizations to align and scale the cost of IT solutions with technology consumption and budget availability.', 
    
    CI1: 'Toastmasters International is a nonprofit educational organization that teaches public speaking and leadership skills through practice, peer feedback and objective evaluation. My chosen path is Persuasive Influence that helps to build skills as an innovative communicator and leader. Focusing on how to negotiate a positive outcome together with building strong interpersonal communication and public speaking skills. You can check each project here.', 
    CI2: 'A study group for technical interviews in IT. In partnership with Brazilians in Tech platform we can provide sessions for a small group of people to do theory review and then practice common code challenges and problems used in interviews. We also provide mock interviews to practice what to say during an interview and get feedback.', 
    CI3: 'Using art and the clown figure we went to the hospitals every week aiming to make this environment a happier place, contributing positively to the humanization of hospitals. You can check the website here to see this amazing volunteer work.',
    
    P1: 'Is the best way to select a film to watch. AI-based for etiam augue luctus, dictumst nisl dolor cras donec scelerisque aliquam luctus. Created with Node, React, MongoDB Is the best way to select a film to watch. AI-based for etiam augue luctus, dictumst nisl dolor cras donec scelerisque aliquam luctus. Created with Node, React, MongoDB Is the best way to select a film to watch. AI-based for etiam augue luctus, dictumst nisl dolor cras donec scelerisque aliquam luctus. Created with Node, React, MongoDB', 
    P2: 'AI - Automated planning. The goal is to save runaway giraffes from the Madagascar ZOO. The domain consists of locals, agents and giraffes. Giraffes are only saved with the help of agents and they go through different danger situations: Drowning; Getting lost in the woods; Fire. Agents can perform certain functions: Lifeguard; Rescuer; Fireman; Caretaker. With the domain implemented, problem files were created, with increasing difficulty, to evaluate the scalability of the planner used. For a better visualization, a graphical interface was developed in Unity in order to animate the solution of the problems, since the solution that the planners return can become overwhelming to understand.', 
    P3: 'In this approach to check weather, sdsd for etiam augue luctus, dictumst nisl dolor cras donec scelerisque aliquam luctus inceptos. Created with Node, React, MongoDB In this approach to check weather, sdsd for etiam augue luctus, dictumst nisl dolor cras donec scelerisque aliquam luctus inceptos. Created with Node, React, MongoDB In this approach to check weather, sdsd for etiam augue luctus, dictumst nisl dolor cras donec scelerisque aliquam luctus inceptos. Created with Node, React, MongoDB'
    
}